name: Build Hello Script

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  run-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run say_hello.sh
        run: bash say_hello.sh
